name: Publish Docker image

on:
  push: {branches: main}
  # release:
  #   types: [published]
jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Build Dockerfile
        run: docker build -t mydeepfont .
