name: Publish Docker image

on:
  push: {branches: main}
  # release:
  #   types: [published]
jobs:
  push_to_registry:
    name: Build Docker image
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Build Dockerfile
        run: docker build -t mydeepfont .
      - name: Train for 1 epoch
        run: docker run -it --rm -v $(pwd):/home/proj/ mydeepfont bash -c 'python3 train.py -e 1'
      - name: Check model file
        run: ls
      - name: Evaluation
        run: docker run -it --rm -v $(pwd):/home/proj/ mydeepfont bash -c 'python3 eval.py'

